# Generated by Django 4.0.2 on 2022-03-01 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da tarefa')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data da criação')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Data de finalização')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.author')),
            ],
        ),
    ]
