# Generated by Django 4.0.3 on 2022-03-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("pilots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilot",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="categories.category",
            ),
            preserve_default=False,
        ),
    ]
