# Generated by Django 4.0.3 on 2022-03-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_active'),
        ('pilots', '0002_pilot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pilots', to='categories.category'),
        ),
    ]
