# Generated by Django 4.0.3 on 2022-03-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nome da empresa')),
                ('since', models.DateField(verbose_name='Fundação da empresa')),
                ('description', models.TextField(verbose_name='Descrição da empresa')),
                ('addition_date', models.DateField(auto_now_add=True, verbose_name='Data de adição')),
                ('state', models.CharField(choices=[('DT', 'Default'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='DT', max_length=20, verbose_name='Estado')),
                ('address', models.CharField(max_length=50, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_name', models.CharField(max_length=20, verbose_name='Nome do quarto/casa')),
                ('description', models.TextField(verbose_name='Descrição do quarto/casa')),
                ('addition_date', models.DateField(auto_now_add=True, verbose_name='Data de adição do quarto/casa')),
                ('times_rented', models.IntegerField(blank=True, default=0, verbose_name='Número de vezes alugado')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('number_of_people', models.IntegerField(verbose_name='Acomodações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.company', verbose_name='Empresa')),
            ],
        ),
    ]
