# Generated by Django 4.0.3 on 2022-03-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da categoria')),
                ('pilots_amount', models.IntegerField(verbose_name='Número máximo de pilotos')),
                ('motorization', models.IntegerField(verbose_name='Potência do motor')),
                ('last_champion', models.CharField(max_length=50, verbose_name='Nome do último campeão')),
            ],
        ),
    ]
