# Generated by Django 4.0.2 on 2022-02-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
